apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-application
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://gitlab.cc-asp.fraunhofer.de/IPT_300/322edge.git
    targetRevision: research-project-thkoeln
    path: manifests/test-login-app  # This should be the root of your Helm chart
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
