apiVersion: v1
data:
  images: |
    - name: "container-registry.gitlab.cc-asp.fraunhofer.de/ipt_300/322edge/research-project-thkoeln"
      tag_selector: "{{ .CI_COMMIT_SHORT_SHA }}"  # Dynamically fetch the tag from GitLab CI commit SHA
      update_strategy: "latest"  # You can use "latest" or other update strategies
  kube.events: "false"
  log.level: info
  registries: |
    - name: "gitlab-registry"
      api_url: "https://container-registry.gitlab.cc-asp.fraunhofer.de"
      username: "mdh02077"
      password: "Fraunhofer@123"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-image-updater-config","app.kubernetes.io/part-of":"argocd-image-updater"},"name":"argocd-image-updater-config","namespace":"argocd"}}
    meta.helm.sh/release-name: argocd-image-updater
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2024-11-25T08:18:46Z"
  labels:
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
    app.kubernetes.io/version: v0.15.1
    helm.sh/chart: argocd-image-updater-0.11.2
  name: argocd-image-updater-config
  namespace: argocd
  resourceVersion: "17064199"
  uid: 0c4409ff-80c7-41b5-a366-82e86bf430a8

