apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-svc
  name: {{ .Release.Name }}-webapp-svc
spec:
  ports:
  - name: webapp-svc
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30007  # Specify the desired NodePort here
  selector:
    app: logindep
  type: NodePort  # Set type to NodePort
status:
  loadBalancer: {}


